apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aurora-inference
  namespace: aurora-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - inference.aurora.aayushmandev.space
    secretName: aurora-inference-tls
  rules:
  - host: inference.aurora.aayushmandev.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aurora-inference
            port:
              number: 80

