apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aurora-inference-canary
  namespace: aurora-system
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx
  rules:
  - host: inference.aurora.aayushmandev.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aurora-inference-canary
            port:
              number: 80

