apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aurora-system

resources:
  - ../base/namespaces
  - ../base/rbac
  - ../workloads/aurora
  - ../workloads/nimbusops-controller
